### ISSUE TITLE
Password Expiration Date/Time

### ISSUE THREAD

**Issue by ranjithckm7** [titlerequired/public#11]
Hi @titlerequired,

I have been trying to add information in $body of the mail about Password Expiration Date/Time, But i end up in different errors. I have tried using(Highlighted parameter and Variable),

$users=get-aduser -filter {(Enabled -eq $true) -and (PasswordNeverExpires -eq $false)} -properties Name, PasswordNeverExpires, PasswordExpired, PasswordLastSet, **msDS-UserPasswordExpiryTimeComputed**, EmailAddress |
Select-Object -Property Name, PasswordNeverExpires, PasswordExpired, PasswordLastSet,**@{Name="ExpiryDate";Expression={[datetime]::FromFileTime($_."msDS-UserPasswordExpiryTimeComputed")}}**,EmailAddress | where { $_.passwordexpired -eq $false }

and 

Write-Output "Process User Objects"
foreach ($user in $users)
{
    # Store User information
    
    $Name = $user.Name
    $emailaddress = $user.emailaddress
    $passwordSetDate = $user.PasswordLastSet
    $samAccountName = $user.SamAccountName
    $pwdLastSet = $user.PasswordLastSet
-->    **$passwordExpiryDate=$user.ExpiryDate**

But getting this error. 
![image](https://user-images.githubusercontent.com/50207308/92473797-b7706000-f1f8-11ea-9e80-331c24f1c048.png)

**Comment by titlerequired** [comment]
Have you tried not doing that?

I suspect this is the primary issue.

`|
Select-Object -Property Name, PasswordNeverExpires, PasswordExpired, PasswordLastSet,@{Name="ExpiryDate";Expression={[datetime]::FromFileTime($_."msDS-UserPasswordExpiryTimeComputed")}},EmailAddress`

**Comment by ranjithckm7** [comment]
Sure. Please advise the alternative way to get the password expiration date/time in $Body of the mail.

**Comment by titlerequired** [comment]
At line 197 all attributes are accessible under $user.

So the datetime the password expires would be $user.ExpiresOn

You cannot link a variable like inside the HTML Section so you would need to define a new variable first to put in the body.

$bodyExpiresOn = $user.ExpiresOn

Then inside $body you can use $bodyExpiresOn wherever you want.

**Comment by ranjithckm7** [comment]
Thanks it worked. Great Work.
