### ISSUE TITLE
Script works when run manually, from scheduled task it only ever skips all users in email notifications

### ISSUE THREAD

**Issue by cf5joe** [titlerequired/public#17]
I installed the script after testing, it works great when I run it manually from the powershell window myself.  I'm using all the same parameters from my manual tests in the scheduled task properties.  However, when I run it manually the script works as desired and users are notified via email according to the threshold I specify.  From a scheduled task, the script runs, log file is created but the action for EVERYONE is "skipped" as if its not considering them in the threshold to be notified.  And yet there are plenty of users who validly need to be notified.  I have logs going back several days that all show the same thing, no email, only ever skipped.  I cannot seem to figure out what is going on.  The parameters I'm using to execute the script are:

powershell.exe-ExecutionPolicy Unrestricted -File "D:\Scripts\AD\PWEXP\PasswordChangeNotification.ps1" -smtpServer send.smtp.com -expireInDays 21 -from "IT Helpdesk <helpdesk@domainredacted.com>" -reportTo emailredacted@domainredacted.com -Logging -LogPath "D:\Scripts\AD\PWEXP\log" -interval 1,2,5,10,15

If I run this manually, as I mentioned everything works great, users get notified.  But from the scheduled task, all I ever see in the logs are "skipped - interval" actions for every user in the list.

**Comment by titlerequired** [comment]
Try using -command not -file

**Comment by geeneo** [comment]
I have the same error.  -command does not work. 


C:\Scripts\PasswordChangeNotification.ps1 : Cannot process argument transformation on parameter 'status'. Cannot convert value "System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept
only Boolean values and numbers, such as $True, $False, 1 or 0.

**Comment by titlerequired** [comment]
That is not the same error.

**Comment by cf5joe** [comment]
So changing it to "-command" did not fix the issue.  It just created new issues for the scheduled task.  I should add that everything else works perfectly in the script, its only an issue if I use the -interval parameter.  Once the interval parameter comes into play, the script never sends emails to the users anymore and everyone is always skipped.  I'm not a coding person so I've been unable to find the problem.

**Comment by cf5joe** [comment]
Also, one more thing.  I tested the interval parameter by using an interval of 1,2,3,4,5,6,7,8,9,10 and ran the script with an initial threshold of 10 days.  The script finds all the users with passwords who expire in less than 10 days and will display/log them when the script runs, but it still marks every one of them as "skipped" in both the email report and the log file.  Something is definitely not right in the interval parameter logic in the script itself.  The screen output when the script runs manually confirms its pulling in the parameter values properly from my command syntax so its not like I'm fat fingering anything.

**Comment by titlerequired** [comment]
The interval parameter logic is basic at best.

At line 234 is where it is processed.

$interval itself, should be an array of numbers. In your case, 1,2,3,4,5,6,7,8,9 and 10. 

Line 236 attempts to convert $user.DaysToExpire into an [int], to be sure it is not stored as a string and store it as $daysToExpire

So, the theory is, that if $daysToExpire (lets say that is 5) is a value in the array $interval, then the interval matches, and the action inside the brackets would be carried out. Otherwise we go to the else statement, where we see it logged as skipped.

So, can you add two lines in at line 258

`$user | Add-Member -MemberType NoteProperty -Name debugDays -Value $daysToExpire
$user | Add-Member -MemberType NoteProperty -Name debugInterval -Value $interval`

Then see what the log shows.

**Comment by cf5joe** [comment]
Done, now in the log the "debugdays" returns a value of a number so that works.  But for "debuginterval" I'm seeing this in the logs:


debugDays | debugInterval
-- | --
18 | System.Object[]
13 | System.Object[]
8 | System.Object[]

Does that help?

**Comment by titlerequired** [comment]
Yes and no, that's an issue with how the array is formatted when it is exported into a CSV.

You could try adding a Start-Transcript <path> -append  at line 69 then add $user at line 280, run the task again and i think that should output what we want to see, but from above only one of those users should be notified?

**Comment by cf5joe** [comment]
I added the two components you mentioned and re-ran the script but I don't see anything else new in the report/log.  Its the same output as the last script run and has the same results.  The 3 lines I copied and pasted earlier was just a snippet of the log, there are many other entries in the log output but I didn't think it would be useful to paste all of them.

**Comment by cf5joe** [comment]
DaysToExpire | ExpiresOn | debugDays | debugInterval | SendMail
-- | -- | -- | -- | --
18 | 1/24/2021 12:21 | 18 | System.Object[] | Skipped - Interval
13 | 1/19/2021 6:39 | 13 | System.Object[] | Skipped - Interval
8 | 1/14/2021 11:46 | 8 | System.Object[] | Skipped - Interval
15 | 1/21/2021 9:16 | 15 | System.Object[] | Skipped - Interval
20 | 1/26/2021 9:00 | 20 | System.Object[] | Skipped - Interval
7 | 1/13/2021 11:42 | 7 | System.Object[] | Skipped - Interval
8 | 1/14/2021 6:05 | 8 | System.Object[] | Skipped - Interval
20 | 1/26/2021 10:24 | 20 | System.Object[] | Skipped - Interval
15 | 1/21/2021 15:00 | 15 | System.Object[] | Skipped - Interval
10 | 1/16/2021 13:56 | 10 | System.Object[] | Skipped - Interval
21 | 1/27/2021 10:55 | 21 | System.Object[] | Skipped - Interval
7 | 1/13/2021 21:32 | 7 | System.Object[] | Skipped - Interval
21 | 1/27/2021 9:31 | 21 | System.Object[] | Skipped - Interval
17 | 1/23/2021 13:04 | 17 | System.Object[] | Skipped - Interval
21 | 1/27/2021 7:52 | 21 | System.Object[] | Skipped - Interval
13 | 1/19/2021 12:40 | 13 | System.Object[] | Skipped - Interval
7 | 1/13/2021 14:00 | 7 | System.Object[] | Skipped - Interval
13 | 1/19/2021 13:57 | 13 | System.Object[] | Skipped - Interval
8 | 1/14/2021 8:41 | 8 | System.Object[] | Skipped - Interval
15 | 1/21/2021 17:46 | 15 | System.Object[] | Skipped - Interval
10 | 1/16/2021 14:42 | 10 | System.Object[] | Skipped - Interval
13 | 1/19/2021 9:41 | 13 | System.Object[] | Skipped - Interval
1 | 1/7/2021 10:57 | 1 | System.Object[] | Skipped - Interval
2 | 1/8/2021 11:58 | 2 | System.Object[] | Skipped - Interval
9 | 1/15/2021 13:21 | 9 | System.Object[] | Skipped - Interval
20 | 1/26/2021 7:54 | 20 | System.Object[] | Skipped - Interval
0 | 1/6/2021 12:33 | 0 | System.Object[] | Skipped - Interval
10 | 1/16/2021 19:25 | 10 | System.Object[] | Skipped - Interval
8 | 1/14/2021 15:11 | 8 | System.Object[] | Skipped - Interval
20 | 1/26/2021 9:51 | 20 | System.Object[] | Skipped - Interval
9 | 1/15/2021 7:13 | 9 | System.Object[] | Skipped - Interval
20 | 1/26/2021 10:46 | 20 | System.Object[] | Skipped - Interval
20 | 1/26/2021 14:52 | 20 | System.Object[] | Skipped - Interval
2 | 1/8/2021 9:00 | 2 | System.Object[] | Skipped - Interval
3 | 1/9/2021 9:07 | 3 | System.Object[] | Skipped - Interval
8 | 1/14/2021 9:24 | 8 | System.Object[] | Skipped - Interval
16 | 1/22/2021 14:08 | 16 | System.Object[] | Skipped - Interval
16 | 1/22/2021 17:06 | 16 | System.Object[] | Skipped - Interval
20 | 1/26/2021 6:23 | 20 | System.Object[] | Skipped - Interval
14 | 1/20/2021 9:56 | 14 | System.Object[] | Skipped - Interval
17 | 1/23/2021 7:13 | 17 | System.Object[] | Skipped - Interval
1 | 1/7/2021 9:01 | 1 | System.Object[] | Skipped - Interval
15 | 1/21/2021 10:51 | 15 | System.Object[] | Skipped - Interval
14 | 1/20/2021 8:20 | 14 | System.Object[] | Skipped - Interval
21 | 1/27/2021 11:08 | 21 | System.Object[] | Skipped - Interval
13 | 1/19/2021 8:00 | 13 | System.Object[] | Skipped - Interval
13 | 1/19/2021 13:26 | 13 | System.Object[] | Skipped - Interval
10 | 1/16/2021 12:46 | 10 | System.Object[] | Skipped - Interval
13 | 1/19/2021 12:34 | 13 | System.Object[] | Skipped - Interval
13 | 1/19/2021 12:08 | 13 | System.Object[] | Skipped - Interval
20 | 1/26/2021 12:08 | 20 | System.Object[] | Skipped - Interval

**Comment by titlerequired** [comment]
Did you get a transcript file generated?

**Comment by cf5joe** [comment]
Yes I did,

**********************
Windows PowerShell transcript start
Start time: 20210106110230
Username: HPCI\user
RunAs User: HPCI\user
Machine: HPCI-CG (Microsoft Windows NT 6.3.9600.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 11092
**********************
Transcript started, output file is C:\Users\user\Documents\PowerShell_transcript.HPCI-CG.rpFEC6AX.20210106110230.
txt
Script Loaded
*** Settings Summary ***
SMTP Server          : send.smtp.com
Expire in Days       : 21
From                 : IT Helpdesk <helpdesk@domain.com>
Logging              : True
Log Path             : D:\Scripts\AD\PWEXP\log
Testing              : False
Test Recipient       :
Report Recipient     : domain.onmicrosoft.com@amer.teams.ms
Intervals            : 1,2,5,10,15
*************************
Found 568 User Objects
Domain Default Password Age: 120
Process User Objects
568 Users processed
51 Users with expiring passwords within 21 Days
Creating Log File
Log Output: D:\Scripts\AD\PWEXP\log\6-1-2021-PasswordLog.csv

I'm omitting the named user output list, but it just dumps all the main headers with information being collected.  It truncates at the end so it doesn't actually show the "Skipped" status.

**Comment by titlerequired** [comment]
Ok, can you change line 280, $user, to $user | select daystoexpire, interval, debugdays

also narrow the interval to one or two days you know should catch people and lower the 21 days to 15.

This should reduce the output generated making it easier to redact.

**Comment by cf5joe** [comment]
Ok I made those changes, but there is no error anywhere, the transcript log is clean, the report/log look normal except for that it still skips everyone even if they match the threshold for a notification based on the interval value.  If I take out the interval parameter, it sends the email notification to everyone if they are at or below the "expireInDays" threshold.  I know this isn't very helpful feedback, but I'm happy to do any other testing you'd like to figure this out.  I really don't want to bombard my users with a daily email.  I really liked the concept of  interval feature of your script

**Comment by Maverickthenoob** [comment]
@cf5joe I was having similar issues. It seems to be all in how the powershell in the scheduled task is formatted.

`-ExecutionPolicy Bypass -noninteractive -Command "& 'C:\scripts\passwordchangenotification.ps1' -smtpServer 'mail.domain.com' -expireInDays 14 -from 'Information Technology <it@domain.com>' -Logging -LogPath 'c:\logFiles' -reportTo 'admin@domain.com' -Interval 1,2,3,7,14"`

This finally got it to work the way I was expecting. I will point out in particular, the type and placement of quotes (specifically -Command "& '...)

I'm new to github (first comment actually) so hopefully this was helpful.

**Comment by cf5joe** [comment]
Maverickthenoob solved it for me.  I would have no way to know the formatting of setting up the scheduled task like this otherwise.  Thank you!  I copied the formatting from below and it works 100% as expected.  The script is finally working as a scheduled task exactly as we wanted.  

-ExecutionPolicy Bypass -noninteractive -Command "& 'C:\scripts\passwordchangenotification.ps1' -smtpServer 'mail.domain.com' -expireInDays 14 -from 'Information Technology <it@domain.com>' -Logging -LogPath 'c:\logFiles' -reportTo 'admin@domain.com' -Interval 1,2,3,7,14"
